-- V1__Create_Loan_Audit_Table.sql
CREATE TABLE IF NOT EXISTS Loan_Audit (
    Id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);