camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  id-generator: strong
  history-level: NONE
  history-level-default: NONE
  filter:
    create: All tasks

camunda.bpm.database:
  jdbc-batch-processing: true

camunda.bpm.job-execution:
  core-pool-size: 20
  max-pool-size: 20

spring.datasource:
  url: "jdbc:postgresql://camunda-database-1.cn160l4t4xyj.us-east-1.rds.amazonaws.com:5432/postgres?socketTimeout=15&options=-c%20statement_timeout=2500"
  username: mycamunda_user
  password: B19yM9Jo25>
  driverClassName: org.postgresql.Driver

spring.datasource.hikari:
  connectionTimeout: 10000
  maximumPoolSize: 25
  poolName: HiCamundaDS

logging.level:
    org.springframework: INFO
    org.camunda.bpm.engine.cmd: DEBUG
    org.camunda.bpm.engine.jobexecutor: DEBUG
    org.camunda.bpm.engine.impl.persistence.entity: INFO