camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  id-generator: strong
  history-level: NONE
  history-level-default: NONE
  job-executor-acquire-by-priority: true
  filter:
    create: All tasks

camunda.bpm.database:
  jdbc-batch-processing: true
  type: postgres

camunda.bpm.job-execution:
  core-pool-size: 50
  max-pool-size: 80
  keep-alive-seconds: 126000
  queue-capacity: 66

spring.datasource:
  url: "jdbc:postgresql://postgres-db:5432/my_camunda"
  username: camunda
  password: camund@123
  driverClassName: org.postgresql.Driver
spring.datasource.hikari:
  connectionTimeout: 10000
  minimumIdle: 40
  maximumPoolSize: 60
  poolName: HiCamundaDS

logging.level:
    org.springframework: INFO
    org.camunda.bpm.engine.cmd: WARN
    org.camunda.bpm.engine.jobexecutor: WARN
    org.camunda.bpm.engine.impl.persistence.entity: WARN