camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  id-generator: strong
  history-level: NONE
  history-level-default: NONE
  filter:
    create: All tasks

camunda.bpm.database:
  jdbc-batch-processing: true

camunda.bpm.job-execution:
  core-pool-size: 10
  max-pool-size: 15

spring.datasource:
  url: "jdbc:postgresql://localhost:5432/my_camunda"
  username: dbuser
  password: admin2021
  driverClassName: org.postgresql.Driver

spring.datasource.hikari:
  connectionTimeout: 10000
  minimumIdle: 25
  maximumPoolSize: 25
  poolName: HiCamundaDS

logging.level:
    org.springframework: INFO
    org.camunda.bpm.engine.cmd: WARN
    org.camunda.bpm.engine.jobexecutor: WARN
    org.camunda.bpm.engine.impl.persistence.entity: WARN